[package]
name = "riteraft"
version = "0.1.0"
authors = ["jopemachine <gbl@lablup.com>"]
edition = "2021"
license = "MIT/Apache-2.0"
repository = "https://github.com/lablup/raftify"
description = ""
keywords = ["raft", "distributed-systems", "ha"]

[dependencies]
async-trait = "0.1.48"
bincode = "1.3"
heed = "0.10.6"
heed-traits = "0.7"
log = { version = "0.4", features = ["std"] }
parking_lot = "0.11"
prost = "0.11"
raft = { git = "https://github.com/jopemachine/raft-rs.git", features = ["prost-codec", "default-logger"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2"
slog-stdlog = "4"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tonic = "0.9"

[build-dependencies]
tonic-build = "0.9"

[workspace]
members = [
    "examples/memstore"
]
